### ISSUE TITLE
Dependency mismatch with PyPI

### ISSUE THREAD

**Issue by JohanMabille** [conda-forge/dash-feedstock#141]
dash has upper bounds on some of its dependencies that the recipe do not have, especially `Flask` and `Werkzeug` (see https://github.com/plotly/dash/blob/dev/requires-install.txt).

I don't know if these bounds are too conservative or if there is an issue with more recent dependencies, but this prevents from running pip check in the test of the recipes.

I got hit by this when packaging [dash-ag-grid](https://github.com/conda-forge/staged-recipes/pull/24346).

**Comment by moorepants** [comment]
This recipe purposely is not as restrictive as the PyPy tarball to minimize difficulties installing it in conda environments. You can pin any dependency more strictly yourself in your conda environment if desired. I don't intend to add the upper bound pins unless it causes actual issues (passing pip check not being one). See https://github.com/conda-forge/dash-feedstock/pull/140 for the latest discussion on this.

**Comment by JohanMabille** [comment]
Thanks for the quick answer, this totally makes sense for me. I just wanted to check it was not a leftover, I am going to follow the same policy in dash-ag-grid.
