### ISSUE TITLE
Feedstock is noarch but Appveyor runs on pull requests.

### ISSUE THREAD

**Issue by moorepants** [conda-forge/dash-feedstock#6]
Issue:
Feedstock is noarch but Appveyor runs on pull requests.
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
@isuruf I'm looking for help on this. Not sure why it is happening.

**Comment by isuruf** [comment]
Fixed

**Comment by isuruf** [comment]
For the record, there were 2 appveyor projects and I deleted one of them

**Comment by moorepants** [comment]
Ok, thank you.
