### ISSUE TITLE
Merge outstanding pull requests

### ISSUE THREAD

**Issue by kevinheavey** [conda-forge/dash-feedstock#64]
There are four outstanding pull requests from regro-cf-autotick-bot for versions 1.5.0, 1.5.1, 1.6.0 and 1.6.1. These are good to merge, right?

Also, how do we get the bot to make a pull request for 1.7.0? It came out over a month ago

**Comment by moorepants** [comment]
The dependencies need to updated manually for each. I just haven't had time to do it.

**Comment by moorepants** [comment]
> Also, how do we get the bot to make a pull request for 1.7.0? It came out over a month ago

i recommend just making a pull request manually.

**Comment by moorepants** [comment]
All outstanding PRs merged.
