### ISSUE TITLE
Need to enforce newer versions of dash dependencies when installing dash

### ISSUE THREAD

**Issue by Keou0007** [conda-forge/dash-feedstock#84]
See conversation [here](https://github.com/plotly/dash/issues/125) and [here](https://github.com/plotly/dash-docs/pull/1003)

The versions of dash-core-components, dash-html-components and dash-table on the main anaconda repo are out of date compared to the version of the dash main package. This leads to problems such as pattern matching callbacks failing silently even though the version requirement for the feature has seemingly been met.

My suggestion is to enforce minimum version requirements of the dependencies for dash main package installs, which I'm guessing/hoping would force newer versions of these dependencies to be moved from conda-forge to the anaconda main repo with future anaconda releases.

**Comment by moorepants** [comment]
The dependencies are pinned here in this feedstock to the specific versions pinned in the main dash source repository. The main issue is really that dash defines their dependencies in a circular way, which is bad practice for python distributions. There is some discussion here that may be relevant: https://github.com/plotly/dash/issues/1062

**Comment by moorepants** [comment]
Also, it looks like you are having issues with dash that is available from the main anaconda repositories. This is the feedstock for the conda-forge packages. You need to open and issue with anaconda to get help with that.

**Comment by Keou0007** [comment]
My assumption here was that packages in the main repo are sourced from conda-forge, so changes here would eventually propagate. Is that not correct?

**Comment by moorepants** [comment]
It's possible that the anaconda team makes use of recipes from conda forge, but I am not aware of any synced occurrence of that. If you want to use the package defined by this feedstock you need to install from the conda forge channel.

If you think that the dependencies in this recipe's feedstock are not properly defined, please point us to the specific discrepancy. Each time I update this feedstock I view the code in the dash source repository and copy the dependency pins to this recipe. I may certainly have made a mistake.

**Comment by Keou0007** [comment]
Ok. That’s useful information. I’ll feed it back to the dash guys and try and get this resolved. Thanks.
