### ISSUE TITLE
Process for updating this feedstock

### ISSUE THREAD

**Issue by moorepants** [conda-forge/dash-feedstock#89]
Dash has an atypical way of setting dependencies in their PyPi released Python distributions (at least for a Python distribution that is used as a library). You can read about this in https://github.com/plotly/dash/issues/1062 if interested. Thus, the purpose of this issue is to describe the current process we use to ensure this feedstock is properly built for conda's dependency resolver.

`dash-feedstock` depends on a number of other conda-forge packages but these four other dash/plotly maintained packages need special attention:

- `dash-core-components-feedstock` https://github.com/conda-forge/dash-core-components-feedstock
- `dash-html-components-feedstock` https://github.com/conda-forge/dash-html-components-feedstock
- `dash-renderer-feedstock` https://github.com/conda-forge/dash-renderer-feedstock
- `dash-table-feedstock` https://github.com/conda-forge/dash-table-feedstock

When a new dash version is released, one or more of the above packages will (almost always) also be released. The dash Python distribution released on PyPi pins to specific version of the above packages (even though the source code in the dash distribution doesn't actually depend on them). You can find those pins in this file in the dash repo:

https://github.com/plotly/dash/blob/dev/requires-install.txt

Make sure to view the `requires-install.txt` file for that specific dash version tag (I select that tag on the github repo then view the file). You'll need to record these pin values.

Steps:

1. The conda-forge autotick bot will recognize newly uploaded dash related packages. Wait for it to make PRs to all of the relevant packages (they usually happen almost simultaneously because they are released almost simultaneously on PyPi).
2. Merge the PRs for the `dash-*-feedstock` packages first. So far, these do not need any attention to their dependencies and you can merge once the conda-forge CI passes. Most are simply wrappers to javascript code and the javascript dependencies are packaged in the Python distribution.
3. Wait a bit for all of the packages to be uploaded to anaconda.org and the CDNs updated so the new packages can be downloaded.
4. Edit the `meta.yaml` file in the `dash-feedstock` PR so that the dependency pins are all correct. You may need to also bump some of the other dependencies too (like flask, etc), but rarely.
5. Once the conda-forge CI passes then you can merge the new Dash version.

Note that I also try to push conda packages for every released version of Dash (not skipping any). Sometimes the dash maintainers will release 2 or 3 dash versions in one day. I do the above process for each version starting with the lowest version number so that all versions of dash are available on conda if someone needs them.

**Comment by wshanks** [comment]
Thanks for posting this and maintaining the feedstocks. I just came here to try to understand why `pip check` was giving me

    dash 1.18.0 has requirement dash-table==4.11.1, but you have dash-table 4.11.0.

and was happy to find that it was already fixed.

**Comment by moorepants** [comment]
With https://github.com/conda-forge/dash-feedstock/pull/96 and Dash 2.0, all the sub-packages are now vendored so this issue should become irrelevant. Once we deal with what to do with the sub-package feedstocks, this can likely be closed.

**Comment by bandersen23** [comment]
Closing since #96 has been merged and we have used a different process several times since 😄
